@route=localhost:4004/odata/v4/main
@id=d28eb7cf-2467-452e-8065-977540638473
@customerId=a738008b-184f-45b3-a370-efed72b86dff
@productId=60de5dbd-5e8f-40a6-b636-54f53521ce39

GET http://{{route}}/SalesOrderHeaders?$filter=id eq '{{id}}'&$expand=items
Content-Type: application/json

###

POST http://{{route}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 390,
    "items": [
        {
            "id": "31644a54-a972-47dd-88d7-2371ad086513",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
          {
            "id": "739cc78c-2450-4c5d-8ff9-a3d964c782f5",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{route}}/SalesOrderHeaders(id='{{id}}')
Content-Type: application/json

###


PUT http://{{route}}/SalesOrderHeaders(id='{{id}}')
Content-Type: application/json

{
   "modifiedBy": "teste",
}

###

# Buscar todos os pedidos maiores ou iguais a 2 milhões

GET http://{{route}}/SalesOrderHeaders?$filter=totalAmount ge 2000000

###

# Buscar todos os pedidos menores ou iguais a 200k

GET http://{{route}}/SalesOrderHeaders?$filter=totalAmount le 200000

###

# Expandindo items, produtos e customers

GET http://{{route}}/SalesOrderHeaders?$expand=items($expand=product),customer

###

# Selecionar somente customer e id do sales order header

GET http://{{route}}/SalesOrderHeaders?$select=id,customer

